### ISSUE TITLE
The discord.py Guide

### ISSUE THREAD

**Issue by Rapptz** [Rapptz/discord.py#7654]
## Introduction

People have often wanted better documentation and a great desire of mine has always been to have a proper guide set up so we could improve the on-boarding experience for newer developers using discord.py. The following are topics that I think would be well fit for an actual guide in using discord.py.

Please note that this isn't a complete list, but it's just something more concrete for people to work on and contribute than just a nebulous "improve the docs" statement.

**Inspiration**:

- [django](https://docs.djangoproject.com/en/4.0/)
- [discord.js's guide](https://discordjs.guide/)
- [Click](https://click.palletsprojects.com/en/8.0.x/)

etc.

## Project Management and Contributing

This is a pretty big undertaking for me to do all the reviews on my own since there are other parts of the library that need attention as well. Therefore, I've assigned two people to do reviews in my stead and once one of them sign off on a PR, I'll give it one final glance before ultimately merging it.

The project managers for this documentation reform are:

- @Gorialis 
- @EvieePy 

### Contributing

The first thing to do, is to join the [official server](https://discord.gg/dpy) and ask me or any of the project managers for the `Documentation` role. This allows you to gain access to where live discussion takes place on how the guide should be worded and other contribution questions.

After you've discussed this in the Discord server, open a PR and give it "Guide" in the title somewhere. It'll be tagged with the `guide` label to let the project managers know what to look at. **The pull request should target the `docs/guide` branch rather than the `master` branch.** Things in the high level overview with a checkbox have already been assigned to someone else!

Note that a PR might be closed if either it is done without consulting in the Discord server first, or it is not sufficiently high quality per my decision or the decision of the project managers. Please remember we all do this on our own free time and we have limited bandwidth but our ultimate goal remains the same: improving the documentation for the sake of others.

## Target Audience

The target audience of the guide is for **intermediate Python programmers**. Basically, people who understand the basics of Python such as classes, functions, and decorators but may not be familiar with asynchronous programming or `asyncio`. The point of this guide is not to teach users how to write Python code.

## The High Level

Ideally we'd rearrange the entire "Getting Started" and FAQ sections into a new page called a guide with a giant TOC to the individual subpages. If Sphinx does not allow for these nested-page TOC then work should be done to allow for that, however *the content comes first*. At some point work will be done in the extension in order to facilitate the complicated table of contents structure necessary for the guide, if this becomes at all needed.

### The Guide

The following is a table of contents for the eventual guide page. These all belong into a root `guide/` directory inside the `docs/` directory. So e.g. `intro.rst` means the file should be located in `docs/guide/intro.rst`.

- [x] Introduction (intro.rst) (#7500)
    - Installing 
    - Virtual Environments
    - [x] Redesign the "Basic Concepts" part.
    - Making an Application
- [x] Getting Started (quickstart.rst) (#7500)
    - This one will walk them through creating a basic bot using the command extension. It should also contain a link to how to get started using application commands if they want that too.
- [ ] Slash Commands and Interactions (interactions/index.rst)
    - [ ] Slash Commands (interactions/slash_commands.rst)
        - This one will go over everything involving how to make or use slash commands.
        - This includes concepts like groups and stuff. This page might end up big!
    - [ ] Context Menu Commands (interactions/context_menus.rst)
        - This is the same but for context menus.
    - [x] Views (interactions/views.rst) (#7507)
        - Everything involving views, buttons, selects, etc.
    - [x] Modals (interactions/modals.rst) (#7507)
        - Everything involving modals
- [x] Popular Topics (topics/index.rst)
    - [ ] Asynchronous Programming (topics/asyncio.rst)
    - [x] Embeds (topics/embeds.rst) (#7498)
        - This would have everything about embeds, e.g. uploading an image to an embed using attachment:// etc.
    - [x] Threads (topics/threads.rst) (#7496)
    - [x] Reactions (topics/reactions.rst) (#7495)
    - [x] Permissions (topics/permissions.rst) (#7497)
        - This includes things like overwrites
    - [x] Intents (topics/intents.rst)
        - Basically move the pre-existing intent guide here.
    - [ ] Partial Models (topics/partials.rst)
        - Everything about partial models.
    - [x] Audit Logs (topics/audit_logs.rst) (#7571)
    - [ ] Webhooks (topics/webhooks.rst)
    - [ ] Waiting for Events or Input (topics/wait_for.rst)
        - Talks about how to use wait_for with your bot
    - [x] Markdown (topics/markdown.rst)
        - Quick guide on markdown.
        - Probably also goes over discord specific implementations
        - Maybe escaping markdown too.
    - [ ] Voice (topics/voice.rst)
        - Discuss FFmpeg / Youtube-DL / Lavalink?
- [x] Sharding (sharding/index.rst) (#7499)
    - AutoShardedClient
    - This could use some fleshing out...
- [ ] Databases (databases.rst)
    - SQLite
    - PostgreSQL
    - JSON
    - MongoDB

## Closing Thoughts

If there is anything needed to discuss this hypothetical TOC, please comment below. I also may have missed *a lot* of things so any suggestions would be more than welcome and doesn't have to be restricted to this list. I just wanted to make a list of things so people would know a general direction in case they want to start writing or contributing but don't know what to do.

**Comment by Luc1412** [comment]
How about implementing #5851.

A possible Deployment guide could cover:
- Free Hosting and why not to use it
- Systemd 
- Docker
- possible other great deployment methods

**Comment by EvieePy** [comment]
I'm not a fan of mentioning anything related to free hosting, as it will likely be too opinionated and a breeding ground for arguments. But that's just my opinion.

It would be nice to see a guide on how to deploy to various operating systems/process managers and the benefits of using them.

**Comment by Tari-dev** [comment]
Djs has guide on clustering,
So it would be nice to have one here as well

**Comment by r-priyam** [comment]
What about adding how to setup a proper working enviroment (including typechecking) to utilise the lib types?

**Comment by AbstractUmbra** [comment]
> What about adding how to setup a proper working enviroment (including typechecking) to utilise the lib types?

I believe most of what's needed here will be covered within the getting started guide that is underway from @XuaTheGrate.
The only addition would be installing `pyright` and using it's command args correctly. Pylance (as part of Visual Studio Code) should work also it utilises `pyright` too.

The only caveat is that dpy is currently only type checks correctly with `pyright`, others such `Mypy` and the JetBrains proprietary one will not work here.

**Comment by alistair-broomhead** [comment]
RE Hosting, I can see that a potentially useful guide might be something like "Here's everything you need to do to set up your bot on a fresh Raspbian install", given how that provides a cheap way to get started, and the skills to expand it out to other hosting?

(I run my own bots off a Raspberry Pi 2 B I found gathering dust at the back of a cupboard, and for small projects it's great)

**Comment by AbstractUmbra** [comment]
> RE Hosting, I can see that a potentially useful guide might be something like "Here's everything you need to do to set up your bot on a fresh Raspbian install", given how that provides a cheap way to get started, and the skills to expand it out to other hosting?
> 
> (I run my own bots off a Raspberry Pi 2 B I found gathering dust at the back of a cupboard, and for small projects it's great)

This is on our collective mental checklist.
This does mostly fall under generic "linux based" setups, so it will get covered. If you can think of other suggestions then feel free to hit us up on the discord server.

**Comment by GoogleGenius** [comment]
Guide on OAuth (like d.js guide)

**Comment by AbstractUmbra** [comment]
> Guide on OAuth (like d.js guide)

discord.py has 0 interactions with OAuth so I don't believe this is something we need to consider?

**Comment by ImNimboss** [comment]
Perhaps a section on looking for async versions of external libraries, if necessary

I have seen a lot of people use, for example, `time.sleep` instead of `asyncio.sleep`, `praw` instead of `asyncpraw`, etc. Depending on the tool, this could have really bad consequences for the bot.

**Comment by nerdguyahmad** [comment]
@ImNimboss That's more of a suitable thing for FAQ and it's already there.

**Comment by AbstractUmbra** [comment]
> Perhaps a section on looking for async versions of external libraries/tools, if necessary
> 
> I have seen a lot of people use, for example, `time.sleep` instead of `asyncio.sleep`, `praw` instead of `asyncpraw`, etc. Depending on the tool, this could have really bad consequences for the bot.

I believe this has been covered at a higher level in the asyncio guide that was done already.

**Comment by ImNimboss** [comment]
Ah, alright

**Comment by alkatar21** [comment]
Maybe you could explain things like `discord.abc.Snowflake` or `discord.Object` and their uses, which at least to me were not immediately clear why they exist and when to use them.

**Comment by RobertCraigie** [comment]
What is the idea for the databases part? Is there going to be a guide for just one database driver / ORM or should there be guides for multiple different database drivers / ORMs?

If there's only going to be guides for a singular database driver / ORM then I'd like to make the case for https://github.com/RobertCraigie/prisma-client-py. 

<details>
<summary>Click to show more context about the benefits and drawbacks of Prisma</summary>

Benefits for using Prisma are:

- Native support for asyncio
- Fully statically typed
- Autocomplete support for queries and returned records
    - [GIF](https://raw.githubusercontent.com/RobertCraigie/prisma-client-py/main/docs/showcase.gif) showcasing autocomplete
    - Supported by any editor that can use pyright as an LSP server
    - Pycharm support was [recently added](https://youtrack.jetbrains.com/issue/PY-40007)
- Supports both SQL and NoSQL database providers, SQLite, PostgreSQL, MongoDB, MySQL, MariaDB and more
- Targets both mypy and pyright with optional pyright specific improvements
    - [Fully recursive types](https://prisma-client-py.readthedocs.io/en/stable/reference/config/#recursive)
- Cross language support
    - Share the same Schema and a very similar API between Python and JS / TS
- Easy to switch database providers

For a fair comparison, here are some drawbacks / situations where you shouldn't use Prisma

- You need low-level control over the database connection(s)
    - The database connections are handled in Rust and are not exposed
    - (You can still write raw SQL queries if you need to)
- You need to make use of types that are not supported yet, such as PostGIS or ltree
	- You can still use these types with Prisma, see the [Prisma documentation](https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#unsupported) for more information.
- The Python client is relatively new, as such there is a lack of online content regarding it, specifically tutorials
    - I am working on writing tutorials myself but it is a slow process
    - The TypeScript Client has been around for a while and is incredibly popular so there is a lot of content regarding that and working with the Prisma Schema file

</details>

Here's an [example ](https://github.com/RobertCraigie/prisma-client-py/tree/main/examples/discord-message-counter) of how Prisma can be used with discord.py. It should be noted that I wrote that example on discord.py `v1.7` and to conform to strict type checking. A more user friendly example would only target basic type checking.

Otherwise if there are going to be guides for many different ORMs then I would be more than happy to contribute a guide for Prisma :)

**Comment by WhoTheOOF** [comment]
> Djs has guide on clustering, So it would be nice to have one here as well

Please.

**Comment by shahriaarrr** [comment]
A guide to working with [/ command](https://github.com/Rapptz/discord.py/blob/master/examples/app_commands/basic.py) should be included in the documentation
@Rapptz

**Comment by remimd** [comment]
Update on this?

I recently started a project with `discord.py`, and in the documentation there's no section that mentions slash commands or views or anything else I've wanted to do. Honestly, it's a pain to have to look in the code or on the Internet to understand how things work.

For a 15k star repository I'm a bit disappointed.

**Comment by AbstractUmbra** [comment]
> Update on this?
> 
> I recently started a project with `discord.py`, and in the documentation there's no section that mentions slash commands or views or anything else I've wanted to do. Honestly, it's a pain to have to look in the code or on the Internet to understand how things work.
> 
> For a 15k star repository I'm a bit disappointed.

There's a whole entire section of the documentation for this:
https://discordpy.readthedocs.io/en/stable/interactions/api.html

As for the guide, no, there's been no work due to the level of work required from the volunteers who would be writing such pieces of the guide. People close to the project have been busy with the non-internet lives and other such things. The people who would be capable of reviewing said work are also in the same boat.
It is open source, so if you want to contribute to it, then PRs welcome stemming from the `docs/guide` branch. You're welcome to look at the [project board](https://github.com/users/Rapptz/projects/2) too.

**Comment by remimd** [comment]
@AbstractUmbra It's just a link to the API description, which doesn't help developers understand what they can do and how.

I know almost nothing about the package, so I'm not the right person to write guides.
In my opinion, it would be a good thing to bring back this topic to make it easier to learn the package.
